//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.MyGatePaymentProcessor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://3dsecure.mygateglobal.com/3DSecure.cfc")]
        public string Woodford_Infrastructure_MyGatePaymentProcessor_MyGate3DSecure_3DSecure1 {
            get {
                return ((string)(this["Woodford_Infrastructure_MyGatePaymentProcessor_MyGate3DSecure_3DSecure1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://enterprise.mygateglobal.com/5x0x0/ePayService.cfc")]
        public string Woodford_Infrastructure_MyGatePaymentProcessor_MyGateEnterprise_ePayService {
            get {
                return ((string)(this["Woodford_Infrastructure_MyGatePaymentProcessor_MyGateEnterprise_ePayService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.mygate.co.za/enterprise/5x0x0/ePayService.cfc")]
        public string Woodford_Infrastructure_MyGatePaymentProcessor_MyGateEnterpriseProduction_ePayService_5x0x2 {
            get {
                return ((string)(this["Woodford_Infrastructure_MyGatePaymentProcessor_MyGateEnterpriseProduction_ePaySer" +
                    "vice_5x0x2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dev-3dsecure.mygateglobal.com/3DSecure.cfc")]
        public string Woodford_Infrastructure_MyGatePaymentProcessor_MyGate3DSecureDEV_3DSecure1 {
            get {
                return ((string)(this["Woodford_Infrastructure_MyGatePaymentProcessor_MyGate3DSecureDEV_3DSecure1"]));
            }
        }
    }
}
