using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Woodford.Core.DomainModel.Models;
using Woodford.Core.Interfaces;

namespace Woodford.Core.ApplicationServices.Commands {
    public class UserEnrollLoyaltyCommand : ICommand {
        public int Id { get; set; }
    }

    public class UserEnrollLoyaltyCommandHandler : ICommandHandler<UserEnrollLoyaltyCommand> {

        private IUserService _userService;
        private INotify _notify;

        public UserEnrollLoyaltyCommandHandler(IUserService userService, INotify notify) {
            _userService = userService;
            _notify = notify;

        }
        public void Handle(UserEnrollLoyaltyCommand command) {
            
            _userService.EnrollLoyalty(command.Id);

            var user = _userService.GetById(command.Id);

            UserRegistrationNotifcationModel emailModel = new UserRegistrationNotifcationModel();
            emailModel.User = user;

            emailModel.HasAutoGeneratedPassword = false;
            emailModel.IsAdminGenerated = false;


            _notify.SendNotifyLoyaltyAccountCreatedByAdmin(emailModel, Setting.Public_Website_Domain);
        }
    }
}
