//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditItemProperty
    {
        public int Id { get; set; }
        public int AuditEntityId { get; set; }
        public string AuditField { get; set; }
        public string CurrentValue { get; set; }
        public string OriginalValue { get; set; }
        public string FieldType { get; set; }
    
        public virtual AuditItem AuditItem { get; set; }
    }
}
