//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditItem()
        {
            this.AuditItemProperties = new HashSet<AuditItemProperty>();
        }
    
        public int Id { get; set; }
        public string Action { get; set; }
        public int EntityId { get; set; }
        public string EntityType { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditItemProperty> AuditItemProperties { get; set; }
    }
}
