//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingHistory
    {
        public int Id { get; set; }
        public string ExternalId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string LicenseNumber { get; set; }
        public string LicenseState { get; set; }
        public Nullable<System.DateTime> LicenseExpiration { get; set; }
        public string Email { get; set; }
        public string MobilePhone { get; set; }
        public string AlternateId { get; set; }
        public int PickupBranchId { get; set; }
        public int DropoffBranchId { get; set; }
        public Nullable<System.DateTime> DateBooked { get; set; }
        public System.DateTime PickupDate { get; set; }
        public System.DateTime DropOffDate { get; set; }
        public Nullable<int> EstimatedKms { get; set; }
        public string RateClass { get; set; }
        public Nullable<int> VehicleGroupId { get; set; }
        public string RateCode { get; set; }
        public Nullable<int> RateCodeId { get; set; }
        public Nullable<int> RentalDays { get; set; }
        public Nullable<int> KmsDriven { get; set; }
        public Nullable<int> FreeKms { get; set; }
        public Nullable<decimal> KmsRate { get; set; }
        public Nullable<decimal> TotalBill { get; set; }
        public Nullable<decimal> LoyaltyPointsEarned { get; set; }
        public Nullable<decimal> TotalForLoyaltyAward { get; set; }
        public Nullable<int> LoyaltyPointTier { get; set; }
        public bool CanEarnPoints { get; set; }
        public bool LoyaltyPointsEarnedEmailSent { get; set; }
        public bool SendLoyaltyPointsEarnedEmail { get; set; }
    }
}
