//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingClaim
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ClaimState { get; set; }
        public System.DateTime BookingPickupDate { get; set; }
        public System.DateTime BookingDropoffDate { get; set; }
        public int BookingPickupBranchId { get; set; }
        public string Email { get; set; }
        public string IdNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int BookingDropOffBranchId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
