//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.BranchVehicles = new HashSet<BranchVehicle>();
            this.InterBranchDropOffFees = new HashSet<InterBranchDropOffFee>();
            this.InterBranchDropOffFees1 = new HashSet<InterBranchDropOffFee>();
            this.LoyaltyTierBenefits = new HashSet<LoyaltyTierBenefit>();
            this.LoyaltyTierBenefits1 = new HashSet<LoyaltyTierBenefit>();
            this.RateAdjustments = new HashSet<RateAdjustment>();
            this.VehicleUpgrades = new HashSet<VehicleUpgrade>();
            this.Rates = new HashSet<Rate>();
            this.BranchRateCodeExclusions = new HashSet<BranchRateCodeExclusion>();
            this.Reservations = new HashSet<Reservation>();
            this.Reservations1 = new HashSet<Reservation>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> FileUploadId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool IsAirport { get; set; }
        public bool IsArchived { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string MapEmbed { get; set; }
        public string AfterHoursTelephoneNumber { get; set; }
        public string PageUrl { get; set; }
        public string BranchSubTitle { get; set; }
        public string BranchAddress { get; set; }
        public string BranchShortDescription { get; set; }
        public string BranchContactPageTitle { get; set; }
        public string BranchContactMetaKeywords { get; set; }
        public string BranchContactMetaDescription { get; set; }
        public string BranchContactPageContent { get; set; }
        public string BranchRequestCallbackPageTitle { get; set; }
        public string BranchRequestCallbackMetaKeywords { get; set; }
        public string BranchRequestCallbackMetaDescription { get; set; }
        public string BranchRequestCallbackPageContent { get; set; }
        public string WeatherApiId { get; set; }
        public Nullable<int> BookingLeadTimeDay { get; set; }
        public Nullable<int> BookingLeadTimeNight { get; set; }
    
        public virtual FileUpload FileUpload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchVehicle> BranchVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterBranchDropOffFee> InterBranchDropOffFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterBranchDropOffFee> InterBranchDropOffFees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoyaltyTierBenefit> LoyaltyTierBenefits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoyaltyTierBenefit> LoyaltyTierBenefits1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateAdjustment> RateAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleUpgrade> VehicleUpgrades { get; set; }
        public virtual BranchSurcharge BranchSurcharge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate> Rates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchRateCodeExclusion> BranchRateCodeExclusions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations1 { get; set; }
    }
}
