//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchSurcharge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BranchSurcharge()
        {
            this.ReservationBranchSurcharges = new HashSet<ReservationBranchSurcharge>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int BranchId { get; set; }
        public decimal SurchargeAmount { get; set; }
        public bool IsOnceOff { get; set; }
        public Nullable<decimal> MaximumCharge { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationBranchSurcharge> ReservationBranchSurcharges { get; set; }
    }
}
