//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public int Id { get; set; }
        public int RateCodeId { get; set; }
        public string Title { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Description { get; set; }
        public string PageUrl { get; set; }
        public Nullable<int> FileUploadId { get; set; }
        public bool IsArchived { get; set; }
        public Nullable<int> SearchResultIconFileUploadId { get; set; }
    
        public virtual FileUpload FileUpload { get; set; }
        public virtual RateCode RateCode { get; set; }
        public virtual FileUpload FileUpload1 { get; set; }
    }
}
