//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountdownSpecial
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string OfferText { get; set; }
        public Nullable<decimal> OfferDiscount { get; set; }
        public Nullable<int> OfferType { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> VehicleUpgradeId { get; set; }
        public Nullable<decimal> VehicleUpgradeAmountOverride { get; set; }
    
        public virtual VehicleUpgrade VehicleUpgrade { get; set; }
    }
}
