//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Woodford2015Entities : DbContext
    {
        public Woodford2015Entities()
            : base("name=Woodford2015Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppSetting> AppSettings { get; set; }
        public virtual DbSet<BranchVehicleExclusion> BranchVehicleExclusions { get; set; }
        public virtual DbSet<BranchVehicle> BranchVehicles { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<Corporate> Corporates { get; set; }
        public virtual DbSet<DynamicPage> DynamicPages { get; set; }
        public virtual DbSet<FileUpload> FileUploads { get; set; }
        public virtual DbSet<HerospaceItem> HerospaceItems { get; set; }
        public virtual DbSet<InterBranchDropOffFee> InterBranchDropOffFees { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<LoyaltyTierBenefit> LoyaltyTierBenefits { get; set; }
        public virtual DbSet<PageContent> PageContents { get; set; }
        public virtual DbSet<RateAdjustment> RateAdjustments { get; set; }
        public virtual DbSet<ReservationsLoyaltyTierBenefit> ReservationsLoyaltyTierBenefits { get; set; }
        public virtual DbSet<ReservationsVehicleExtra> ReservationsVehicleExtras { get; set; }
        public virtual DbSet<VehicleExtra> VehicleExtras { get; set; }
        public virtual DbSet<VehicleGroup> VehicleGroups { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<MessageQueue> MessageQueues { get; set; }
        public virtual DbSet<Waiver> Waivers { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<CountdownSpecial> CountdownSpecials { get; set; }
        public virtual DbSet<VehicleUpgrade> VehicleUpgrades { get; set; }
        public virtual DbSet<NewsCategory> NewsCategories { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<UrlRedirect> UrlRedirects { get; set; }
        public virtual DbSet<AuditItem> AuditItems { get; set; }
        public virtual DbSet<AuditItemProperty> AuditItemProperties { get; set; }
        public virtual DbSet<RateRule> RateRules { get; set; }
        public virtual DbSet<RateCode> RateCodes { get; set; }
        public virtual DbSet<BranchSurcharge> BranchSurcharges { get; set; }
        public virtual DbSet<Rate> Rates { get; set; }
        public virtual DbSet<CorporateRateCode> CorporateRateCodes { get; set; }
        public virtual DbSet<LoyaltyTier> LoyaltyTiers { get; set; }
        public virtual DbSet<BranchRateCodeExclusion> BranchRateCodeExclusions { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<ReservationBranchSurcharge> ReservationBranchSurcharges { get; set; }
        public virtual DbSet<BookingHistory> BookingHistories { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<EmailSignature> EmailSignatures { get; set; }
        public virtual DbSet<EmailSignatureCampaign> EmailSignatureCampaigns { get; set; }
        public virtual DbSet<MyGateRefundTransaction> MyGateRefundTransactions { get; set; }
        public virtual DbSet<Refund> Refunds { get; set; }
        public virtual DbSet<BookingClaim> BookingClaims { get; set; }
        public virtual DbSet<TrustPilotReviewInvite> TrustPilotReviewInvites { get; set; }
        public virtual DbSet<VehicleManufacturer> VehicleManufacturers { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<MyGateTransaction> MyGateTransactions { get; set; }
        public virtual DbSet<ReservationsAdmin> ReservationsAdmins { get; set; }
    }
}
