//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSignature
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FixedContact { get; set; }
        public string CellContact { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
        public string SeniorName { get; set; }
        public string SeniorFixedContact { get; set; }
        public string SeniorCellContact { get; set; }
        public string SeniorEmail { get; set; }
        public string DirectorName { get; set; }
        public string DirectorEmail { get; set; }
        public bool ShowSidePanel { get; set; }
    }
}
