//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileUpload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileUpload()
        {
            this.Campaigns = new HashSet<Campaign>();
            this.HerospaceItems = new HashSet<HerospaceItem>();
            this.VehicleGroups = new HashSet<VehicleGroup>();
            this.Vehicles = new HashSet<Vehicle>();
            this.Vehicles1 = new HashSet<Vehicle>();
            this.Branches = new HashSet<Branch>();
            this.News = new HashSet<News>();
            this.EmailSignatureCampaigns = new HashSet<EmailSignatureCampaign>();
            this.EmailSignatureCampaigns1 = new HashSet<EmailSignatureCampaign>();
            this.EmailSignatureCampaigns2 = new HashSet<EmailSignatureCampaign>();
            this.EmailSignatureCampaigns3 = new HashSet<EmailSignatureCampaign>();
            this.EmailSignatureCampaigns4 = new HashSet<EmailSignatureCampaign>();
            this.EmailSignatureCampaigns5 = new HashSet<EmailSignatureCampaign>();
            this.VehicleManufacturers = new HashSet<VehicleManufacturer>();
            this.Campaigns1 = new HashSet<Campaign>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public byte[] FileContent { get; set; }
        public string FileExtension { get; set; }
        public System.DateTime DateUploaded { get; set; }
        public string FileContext { get; set; }
        public string MimeType { get; set; }
        public bool IsStandalone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campaign> Campaigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HerospaceItem> HerospaceItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleGroup> VehicleGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSignatureCampaign> EmailSignatureCampaigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSignatureCampaign> EmailSignatureCampaigns1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSignatureCampaign> EmailSignatureCampaigns2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSignatureCampaign> EmailSignatureCampaigns3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSignatureCampaign> EmailSignatureCampaigns4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailSignatureCampaign> EmailSignatureCampaigns5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleManufacturer> VehicleManufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campaign> Campaigns1 { get; set; }
    }
}
