//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.MyGateRefundTransactions = new HashSet<MyGateRefundTransaction>();
            this.Refunds = new HashSet<Refund>();
            this.MyGateTransactions = new HashSet<MyGateTransaction>();
        }
    
        public int Id { get; set; }
        public int ReservationId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public decimal AmountPaid { get; set; }
        public bool IsMobileCheckout { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsCorporateCheckout { get; set; }
        public string PaymentErrorCode { get; set; }
        public bool HasPaymentError { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyGateRefundTransaction> MyGateRefundTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refund> Refunds { get; set; }
        public virtual Reservation Reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyGateTransaction> MyGateTransactions { get; set; }
    }
}
