//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyaltyTierBenefit
    {
        public int Id { get; set; }
        public int LoyaltyTierId { get; set; }
        public int BenefitTypeId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> DropOffGraceHours { get; set; }
        public Nullable<int> PickupLocationId { get; set; }
        public Nullable<int> DropOffLocationId { get; set; }
        public Nullable<int> FreeKms { get; set; }
        public Nullable<int> FreeDays { get; set; }
        public Nullable<int> UpgradeId { get; set; }
        public Nullable<int> ExtraId { get; set; }
        public Nullable<decimal> ExtraPriceOverride { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual VehicleExtra VehicleExtra { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Branch Branch1 { get; set; }
        public virtual VehicleUpgrade VehicleUpgrade { get; set; }
        public virtual LoyaltyTier LoyaltyTier { get; set; }
    }
}
