//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageQueue
    {
        public int Id { get; set; }
        public string SenderProcess { get; set; }
        public string EmailTo { get; set; }
        public string EmailCc { get; set; }
        public string EmailBcc { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public bool Sent { get; set; }
        public bool Processing { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public int TimesTried { get; set; }
        public Nullable<bool> ErrorOccurred { get; set; }
        public string ErrorMessage { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool HasAttachment { get; set; }
        public string AttachementPath { get; set; }
    }
}
