//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyGateTransaction
    {
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public string MyGateAuthorisationIDAuth { get; set; }
        public string MyGateAuthorisationIDCapt { get; set; }
        public Nullable<System.Guid> MyGateTransactionID { get; set; }
        public string MyGate3DParEq { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
