//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Headline { get; set; }
        public string SubHeadline { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> FileUploadId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Author { get; set; }
        public bool IsArchived { get; set; }
        public int NewsCategoryId { get; set; }
        public string PageUrl { get; set; }
    
        public virtual FileUpload FileUpload { get; set; }
        public virtual NewsCategory NewsCategory { get; set; }
    }
}
