//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageContent
    {
        public int Id { get; set; }
        public string PageTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string PageContent1 { get; set; }
        public Nullable<int> DynamicPageId { get; set; }
        public Nullable<int> VehicleGroupId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> NewsId { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> VehicleManufacturerId { get; set; }
    }
}
