//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RateCode()
        {
            this.Campaigns = new HashSet<Campaign>();
            this.RateAdjustments = new HashSet<RateAdjustment>();
            this.Rates = new HashSet<Rate>();
            this.CorporateRateCodes = new HashSet<CorporateRateCode>();
            this.BranchRateCodeExclusions = new HashSet<BranchRateCodeExclusion>();
        }
    
        public int Id { get; set; }
        public bool AvailableToPublic { get; set; }
        public bool AvailableToLoyalty { get; set; }
        public bool AvailableToCorporate { get; set; }
        public bool IsNotAdjustable { get; set; }
        public string Title { get; set; }
        public int RateRuleId { get; set; }
        public bool CanHaveUpgradeApplied { get; set; }
        public bool IsSticky { get; set; }
        public string ColorCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campaign> Campaigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateAdjustment> RateAdjustments { get; set; }
        public virtual RateRule RateRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate> Rates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorporateRateCode> CorporateRateCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchRateCodeExclusion> BranchRateCodeExclusions { get; set; }
    }
}
