//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RateRule()
        {
            this.RateCodes = new HashSet<RateCode>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string DaysOfWeek { get; set; }
        public int MinDays { get; set; }
        public int MaxDays { get; set; }
        public Nullable<int> FreeKmsPerDay { get; set; }
        public Nullable<int> RateTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateCode> RateCodes { get; set; }
    }
}
