//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int Id { get; set; }
        public int VehicleGroupId { get; set; }
        public int RateCodeId { get; set; }
        public int BranchId { get; set; }
        public Nullable<System.DateTime> ValidStartDate { get; set; }
        public Nullable<System.DateTime> ValidEndDate { get; set; }
        public decimal Price { get; set; }
        public bool IsOpenEnded { get; set; }
        public decimal CostPerKm { get; set; }
        public bool IsDeleted { get; set; }
        public int FreeKms { get; set; }
        public bool HasUnlimitedKms { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual RateCode RateCode { get; set; }
        public virtual VehicleGroup VehicleGroup { get; set; }
    }
}
