//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateAdjustment
    {
        public int Id { get; set; }
        public int AdjustmentTypeEnum { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int BranchId { get; set; }
        public Nullable<int> VehicleGroupId { get; set; }
        public Nullable<int> RateCodeId { get; set; }
        public Nullable<int> NumberOfBookings { get; set; }
        public decimal AdjustmentPercentage { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsArchived { get; set; }
    
        public virtual VehicleGroup VehicleGroup { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual RateCode RateCode { get; set; }
    }
}
