//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int ReportType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public bool UseCurrentDateAsStartDate { get; set; }
        public Nullable<int> DateUnitsToAdd { get; set; }
        public Nullable<int> DateUnitType { get; set; }
        public string ReportFilter { get; set; }
    }
}
