//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationBranchSurcharge
    {
        public int Id { get; set; }
        public int ReservationId { get; set; }
        public int BranchSurchargeId { get; set; }
        public string Title { get; set; }
        public bool IsOnceOff { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> MaximumCharge { get; set; }
    
        public virtual BranchSurcharge BranchSurcharge { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
