//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationsLoyaltyTierBenefit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservationsLoyaltyTierBenefit()
        {
            this.ReservationsVehicleExtras = new HashSet<ReservationsVehicleExtra>();
        }
    
        public int Id { get; set; }
        public int ReservationId { get; set; }
        public int LoyaltyTierBenefitId { get; set; }
        public int BenefitTypeId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> DropOffGraceHours { get; set; }
        public Nullable<int> FreeKms { get; set; }
        public Nullable<int> FreeDays { get; set; }
        public Nullable<int> UpgradeId { get; set; }
        public Nullable<int> ExtraId { get; set; }
        public Nullable<decimal> ExtraPriceOverride { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationsVehicleExtra> ReservationsVehicleExtras { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
