//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Refunds = new HashSet<Refund>();
            this.Refunds1 = new HashSet<Refund>();
            this.ReservationBranchSurcharges = new HashSet<ReservationBranchSurcharge>();
            this.ReservationsLoyaltyTierBenefits = new HashSet<ReservationsLoyaltyTierBenefit>();
            this.ReservationsVehicleExtras = new HashSet<ReservationsVehicleExtra>();
            this.TrustPilotReviewInvites = new HashSet<TrustPilotReviewInvite>();
        }
    
        public int Id { get; set; }
        public System.DateTime PickupDate { get; set; }
        public System.DateTime DropOffDate { get; set; }
        public int PickupBranchId { get; set; }
        public int DropOffBranchId { get; set; }
        public int VehicleId { get; set; }
        public decimal VehicleExcess { get; set; }
        public decimal VehicleDeposit { get; set; }
        public int RateId { get; set; }
        public int RateCodeId { get; set; }
        public string RateCodeTitle { get; set; }
        public decimal RatePrice { get; set; }
        public Nullable<int> RateAdjustmentId { get; set; }
        public Nullable<int> RateAdjustmentType { get; set; }
        public Nullable<decimal> RateAdjustmentPercentage { get; set; }
        public decimal ContractFee { get; set; }
        public decimal DropOffFee { get; set; }
        public Nullable<int> VehicleUpgradeId { get; set; }
        public Nullable<int> UpgradedVehicleId { get; set; }
        public Nullable<decimal> VehicleUpgradePrice { get; set; }
        public Nullable<int> CountdownSpecialId { get; set; }
        public Nullable<int> CountdownSpecialType { get; set; }
        public string CountdownSpecialOfferText { get; set; }
        public Nullable<decimal> CountdownSpecialDiscount { get; set; }
        public Nullable<decimal> CountdownSpecialVehicleUpgradePriceOverride { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string IdNumber { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> VoucherId { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<int> VoucherRewardType { get; set; }
        public string VoucherRewardText { get; set; }
        public Nullable<decimal> VoucherRewardDiscount { get; set; }
        public Nullable<decimal> VoucherRewardDiscountPercentage { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int ReservationState { get; set; }
        public decimal TaxRate { get; set; }
        public Nullable<int> BranchSurchargeId { get; set; }
        public string BranchSurchageText { get; set; }
        public Nullable<decimal> BranchSurchageTotalPrice { get; set; }
        public bool IsCorporate { get; set; }
        public Nullable<int> CorporateId { get; set; }
        public bool ReminderSent { get; set; }
        public bool ReminderSMSSent { get; set; }
        public bool ThankYouSent { get; set; }
        public bool LoyaltyPointsAssigned { get; set; }
        public Nullable<decimal> LoyaltyPointsEarned { get; set; }
        public Nullable<decimal> LoyaltyPointsSpent { get; set; }
        public Nullable<int> LoyaltyTierAtTimeOfBooking { get; set; }
        public string QuoteReference { get; set; }
        public Nullable<System.DateTime> QuoteSentDate { get; set; }
        public bool HasBeenModified { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsQuote { get; set; }
        public bool QuoteReminderSent { get; set; }
        public bool AddedToExternalSystem { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public bool IsArchived { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<decimal> CancellationFee { get; set; }
        public Nullable<decimal> RefundedAmount { get; set; }
        public int PaymentProviderType { get; set; }
        public string PaymentErrorCode { get; set; }
        public bool HasPaymentError { get; set; }
        public string PaymentErrorMessage { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Branch Branch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refund> Refunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refund> Refunds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationBranchSurcharge> ReservationBranchSurcharges { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual VehicleUpgrade VehicleUpgrade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationsLoyaltyTierBenefit> ReservationsLoyaltyTierBenefits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationsVehicleExtra> ReservationsVehicleExtras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrustPilotReviewInvite> TrustPilotReviewInvites { get; set; }
    }
}
