//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationsVehicleExtra
    {
        public int Id { get; set; }
        public int ReservationId { get; set; }
        public int VehicleExtraId { get; set; }
        public decimal ExtraPrice { get; set; }
        public string ExtraTitle { get; set; }
        public Nullable<int> ReservationLoyaltyTierBenefitId { get; set; }
    
        public virtual VehicleExtra VehicleExtra { get; set; }
        public virtual ReservationsLoyaltyTierBenefit ReservationsLoyaltyTierBenefit { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
