//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrustPilotReviewInvite
    {
        public int Id { get; set; }
        public Nullable<int> ReservationId { get; set; }
        public Nullable<int> VoucherId { get; set; }
        public bool VoucherSent { get; set; }
        public Nullable<System.DateTime> VoucherSentDate { get; set; }
        public string Email { get; set; }
    
        public virtual Voucher Voucher { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
