//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProfile()
        {
            this.webpages_Roles = new HashSet<webpages_Roles>();
            this.BookingClaims = new HashSet<BookingClaim>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> CorporateId { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int LoyaltyTierId { get; set; }
        public Nullable<System.DateTime> LoyaltyPeriodStart { get; set; }
        public Nullable<System.DateTime> LoyaltyPeriodEnd { get; set; }
        public string IdNumber { get; set; }
        public bool IsLoyaltyMember { get; set; }
        public Nullable<System.DateTime> LoyaltySignUpDate { get; set; }
        public string ExistingLoyaltyNumber { get; set; }
        public bool HasExistingLoyaltyNumber { get; set; }
        public bool IsAccountDisabled { get; set; }
        public bool IsLoyaltyTierLocked { get; set; }
    
        public virtual Corporate Corporate { get; set; }
        public virtual LoyaltyTier LoyaltyTier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingClaim> BookingClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
