//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.BranchVehicles = new HashSet<BranchVehicle>();
            this.VehicleUpgrades = new HashSet<VehicleUpgrade>();
            this.VehicleUpgrades1 = new HashSet<VehicleUpgrade>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int VehicleGroupId { get; set; }
        public bool IsArchived { get; set; }
        public Nullable<int> FileUploadId { get; set; }
        public Nullable<int> FileUploadId2 { get; set; }
        public string PageUrl { get; set; }
        public string ShortDescription { get; set; }
        public int NumberOfPassengers { get; set; }
        public int NumberOfBaggage { get; set; }
        public bool IsPetrol { get; set; }
        public bool HasAircon { get; set; }
        public bool HasRadio { get; set; }
        public bool HasPowerSteering { get; set; }
        public bool IsAutomatic { get; set; }
        public decimal ExcessAmount { get; set; }
        public decimal DepositAmount { get; set; }
        public int SortOrder { get; set; }
        public Nullable<int> VehicleManufacturerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchVehicle> BranchVehicles { get; set; }
        public virtual FileUpload FileUpload { get; set; }
        public virtual FileUpload FileUpload1 { get; set; }
        public virtual VehicleGroup VehicleGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleUpgrade> VehicleUpgrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleUpgrade> VehicleUpgrades1 { get; set; }
        public virtual VehicleManufacturer VehicleManufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
