//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woodford.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            this.TrustPilotReviewInvites = new HashSet<TrustPilotReviewInvite>();
        }
    
        public int Id { get; set; }
        public bool RequireClientValidation { get; set; }
        public string ClientName { get; set; }
        public string ClientEmail { get; set; }
        public System.DateTime DateIssued { get; set; }
        public System.DateTime DateExpiry { get; set; }
        public Nullable<System.DateTime> DateRedeemed { get; set; }
        public Nullable<int> ReservationId { get; set; }
        public string VoucherNumber { get; set; }
        public int VoucherRewardType { get; set; }
        public Nullable<decimal> VoucherDiscount { get; set; }
        public string VoucherReward { get; set; }
        public Nullable<decimal> VoucherDiscountPercentage { get; set; }
        public bool IsMultiUse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrustPilotReviewInvite> TrustPilotReviewInvites { get; set; }
    }
}
